# Generated by Django 4.1 on 2022-08-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_customer_order_transactiondetails_shippingaddress_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="phone",
            field=models.CharField(default=254791055897, max_length=12),
            preserve_default=False,
        ),
    ]
