# Generated by Django 4.1 on 2022-08-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_customer_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactiondetails",
            name="transaction_code",
        ),
        migrations.AddField(
            model_name="transactiondetails",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="transactiondetails",
            name="is_finished",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transactiondetails",
            name="is_succesful",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transactiondetails",
            name="phone_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="transactiondetails",
            name="receipt_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="transactiondetails",
            name="request_id",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
