# Generated by Django 4.1 on 2022-08-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
