# Generated by Django 4.1 on 2022-08-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_reply"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reply",
            old_name="reply",
            new_name="body",
        ),
        migrations.AddField(
            model_name="reply",
            name="subject",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
