# Generated by Django 4.1.3 on 2022-11-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_shippingaddress_estate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image_filename',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
