# Generated by Django 4.1.3 on 2022-11-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_product_image_product_image_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
